import { ProductCardInterface } from "../components/cards/ProductCard";

const allProducts: Array<ProductCardInterface> = [
    {
        name: 'Product 1',
        width: 4,
        height: 5,
        category: 'Cotton Bags',
        subCategory: 'Cotton Laundry Bags',
        _id: '1',
        image: '/product-images/IMG-20250224-WA0001.jpg',
        material: 'Cotton Canvas',
        capacity: '700 gm',
        quantity: '100',
        price: '40',
        weight: '150 gm',
    },
    {
        name: 'Product 2',
        width: 4,
        height: 5,
        category: 'Cotton Bags',
        subCategory: 'Cotton Laundry Bags',
        _id: '2',
        image: '/product-images/IMG-20250224-WA0002.jpg',
        material: 'Cotton',
        capacity: '650 gm',
        quantity: '120',
        price: '50',
        weight: '120 gm',
    },
    {
        name: 'Product 3',
        width: 4,
        height: 5,
        category: 'Jute Bags',
        subCategory: 'Jute Promotional Bags',
        _id: '3',
        image: '/product-images/IMG-20250224-WA0003.jpg',
        material: 'Jute',
        capacity: '700 gm',
        quantity: '100',
        price: '70',
        weight: '120 gm',
        pattern: 'Plain , Printed',
    },
    {
        name: 'Product 4',
        width: 4,
        height: 5,
        category: 'Jute Bags',
        subCategory: 'Jute Promotional Bags',
        _id: '4',
        image: '/product-images/IMG-20250224-WA0004.jpg',
        material: 'Jute',
        capacity: '600 gm',
        quantity: '200',
        price: '68',
        weight: '5 kg',
    },
    {
        name: 'Product 5',
        width: 4,
        height: 5,
        category: 'Juco Bags',
        _id: '5',
        image: '/product-images/IMG-20250224-WA0005.jpg',
        material: 'Juco',
        capacity: '600 gm',
        quantity: '200',
        price: '50',
        weight: '5 kg',
    },
    {
        name: 'Product 6',
        width: 4,
        height: 5,
        category: 'Juco Bags',
        _id: '6',
        image: '/product-images/IMG-20250224-WA0006.jpg',
        material: 'Jute',
        capacity: '600 gm',
        quantity: '200',
        price: '72',
        weight: '5 kg',
    },
    {
        name: 'Product 7',
        width: 4,
        height: 5,
        category: 'Cotton Bags',
        subCategory: 'Cotton Shopping Bags',
        _id: '7',
        image: '/product-images/IMG-20250224-WA0007.jpg',
        material: 'Cotton',
        capacity: '300 gm',
        quantity: '150',
        price: '45',
        weight: '700 gm',
    },
]

export default allProducts;